fix for gcc 10
error after updating to gcc 10.3.1:
src/zimg/colorspace/matrix3.cpp:45:7: error: 'size_t' was not declared in this scope; did you mean 'std::size_t'?
    45 |  for (size_t i = 0; i < 3; ++i) {
       |       ^~~~~~
       |       std::size_t
 In file included from /usr/include/c++/10.3.1/utility:68,
                  from /usr/include/c++/10.3.1/array:38,
                  from src/zimg/colorspace/matrix3.h:6,
                  from src/zimg/colorspace/matrix3.cpp:1:

refer to: https://bugs.gentoo.org/721676